### ISSUE TITLE
Will you be adding advanced topics notebooks as well ?

### ISSUE THREAD

**Issue by anuragreddygv323** [MaurizioFD/RecSys_Course_2018#1]
Advanced topics
Deep Learning algorithms
Context-aware recommenders
Learning to rank
Cross-domain recommenders
Interfaces for recommender systems: elicitation and explanation

**Comment by MaurizioFD** [comment]
Hello,

The notebooks are related to the course program, whose practice sessions will not cover those topics. 
Note that you will find an implementation of BPR (learning to rank) for SLIM and Matrix Factorization
